# Solve Any Data Analysis Problem

## Chapter 5 - Project 4 - Example solution - Part 1 (alternative)

We need to find and extract:

- annual admissions breakdown
- breakdown of genre
- breakdown of distributors

Figure out where relevant tables are for a few years (2018 onwards so we have both pre- and "post-" COVID periods)

Process to install the `camelot` library:

- install Ghostscript (https://camelot-py.readthedocs.io/en/master/user/install-deps.html#install-deps)
- install Tkinter if not already installed (https://www.activestate.com/products/tcl/)
- install `camelot` (at time of writing, one of its dependencies currently requires Python 3.9 so is incompatible with newer versions)

In [1]:
import numpy as np
import pandas as pd

import camelot

from IPython.display import display

Let's create a reusable function to extract and print all the tables in a PDF

In [2]:
def extract_tables(pdf_path, pages="all", print_tables=True):
    """
    Extract all tables found in a PDF.
    
    `pdf_path`: file path pointing to the PDF
    `pages`: the page number(s) to read
    `print_tables`: whether to also print out all the tables that are found (default: True)
    
    returns: a list of pandas DataFrames
    """
    
    print(f"Reading {pdf_path}")
    
    tables = camelot.read_pdf(pdf_path, pages=pages, flavor="stream")
    
    print(f"{tables.n} tables found.")
    
    if tables.n > 0:
        dataframes = [table.df for table in tables]
        
        if print_tables:
            for index, df in enumerate(dataframes):
                print(f"\n##########################\n\tTable {index}\n##########################\n")
                display(df)
    
        return dataframes
    return []

# 2018

For 2018 all necessary tables are in the same PDF so let's extract them all here.

In [3]:
tables_2018 = extract_tables("./files/2019 - BFI yearbook 2019 - 888.pdf", pages="11,34,70")

Reading ./files/2019 - BFI yearbook 2019 - 888.pdf
4 tables found.

##########################
	Table 0
##########################

,0,1,2,3
0,"Table 2 Monthly UK cinema admissions, 2017 and...",,,
1,Month,2017 (million),2018 (million),% +/- on 2017
2,January,15.0,16.2,8.0
3,February,16.5,16.1,-2.3
4,March,16.2,13.5,-16.2
5,April,15.6,15.5,-0.9
6,May,11.3,13.7,21.0
7,June,9.6,10.4,8.6
8,July,17.8,15.6,-12.3
9,August,14.5,19.2,32.8
10,September,10.8,10.1,-6.0
11,October,12.1,16.0,32.6
12,November,14.1,14.8,5.4
13,December,17.2,15.7,-8.7
14,Total,170.6,177.0,3.7
15,"Source: CAA, comScore",,,

##########################
	Table 1
##########################

,0,1,2,3,4,5
0,Table 17 Films released in the UK and Republic...,,,,,
1,Genre,Number of,% of,Gross box,% of total,Top performing title
2,,releases,releases,office,box office,
3,,,,(£ million),,
4,Action,77,9.8,361.3,27.7,Avengers: Infinity War
5,Animation,46,5.8,242.2,18.6,Incredibles 2
6,Drama,246,31.3,154.1,11.8,A Star Is Born
7,Comedy,144,18.3,88.3,6.8,Johnny English Strikes Again
8,Biopic,5,0.6,78.5,6.0,Bohemian Rhapsody
9,Musical,5,0.6,67.0,5.1,Mamma Mia! Here We Go Again
10,Family,10,1.3,60.3,4.6,Mary Poppins Returns
11,Fantasy,4,0.5,57.6,4.4,Fantastic Beasts: The Crimes of Grindelwald
12,Horror,38,4.8,57.1,4.4,A Quiet Place
13,Adventure,10,1.3,36.4,2.8,Ready Player One
14,Sci-fi,14,1.8,30.8,2.4,Solo: A Star Wars Story
15,Thriller,42,5.3,30.6,2.3,The Equalizer 2
16,Crime,10,1.3,17.9,1.4,Widows
17,Romance,17,2.2,11.8,0.9,The Guernsey Literary and Potato Peel Pie Society
18,Documentary,112,14.2,9.3,0.7,Free Solo
19,War,3,0.4,1.3,0.1,Journey’s End
20,Western,2,0.3,0.1,<0.1,Sweet Country
21,Mystery,2,0.3,0.1,<0.1,Dark River
22,Total,787,100.0,"1,304.8",100.0,
23,"Source: comScore, BFI RSU analysis",,,,,

##########################
	Table 2
##########################

,0,1
0,DISTRIBUTORS,cinemas into 2018. The top earning distributor...
1,,"Disney, which handled seven of the top 20 rele..."
2,The top 10 feature film distributors had a 95....,"2018 including Avengers: Infinity War, Incredi..."
3,the market in 2018 from the release of 251 tit...,"Black Panther, as well as Star Wars: The Last ..."
4,all films on release). The same 10 distributor...,December 2017 release which continued to generate
5,market share of 96% in 2017 from 284 releases ...,significant box office in 2018. (The 24% box o...
6,releases). A further 128 film distributors wer...,generated by Walt Disney in 2018 is the highes...
7,the theatrical release of films in the UK and ...,achieved by a single distributor since our rec...
8,"Ireland in 2018, compared with 117 companies o...",The second highest earning distributor was Uni...
9,top 10 in 2017. These distributors handled a t...,which released four of 2018’s top 20 titles in...
10,titles (74% of all releases) but generated onl...,"Mamma Mia! Here We Go Again, Jurassic World: F..."
11,total box office.,Kingdom and The Grinch.
12,Table 1 shows box office takings by distributo...,The top earning independent distributor in 201...
13,"on release during 2018, and hence includes rev...","Films, whose highest grossing titles were The ..."
14,titles which were released in 2017 but remaine...,House With a Clock in Its Walls and Finding Yo...

##########################
	Table 3
##########################

,0,1,2,3
0,"on release during 2018, and hence includes rev...",,"Films, whose highest grossing titles were The ...",
1,titles which were released in 2017 but remaine...,,House With a Clock in Its Walls and Finding Yo...,
2,,"Table 1 Distributor share of box office, UK an...",,
3,Distributor,Market share,Films on release,Box office gross
4,,(%),in 2018,(£ million)
5,Walt Disney,23.6,24,325.6
6,Universal,19.5,40,268.5
7,20th Century Fox,14.5,28,199.3
8,Warner Bros,13.9,31,191.4
9,Sony,10.7,33,146.8
10,Paramount,4.8,12,66.0
11,eOne Films,3.2,22,43.9
12,StudioCanal,2.8,31,38.4
13,Lionsgate,1.5,21,21.2
14,Entertainment,1.1,9,15.6
15,Top 10 total,95.5,251,"1,316.8"
16,Others (128 distributors),4.5,715,61.4
17,Total,100.0,966,"2,695.0"
18,Source: comScore,,,

Looks like the first table is the monthly breakdown we're looking for.

<span style="color:red">Mention insertion of `Year` everywhere</span>

In [4]:
admissions_2018 = (
    tables_2018[0]
    .loc[2:13,[0, 2]] # drop first two and last two rows, keep month and 2018 admissions column
)

admissions_2018.columns = ["Month", "Admissions (million)"]

admissions_2018.insert(0, "Year", 2018)

admissions_2018.head()

   Year     Month Admissions (million)
2  2018   January                 16.2
3  2018  February                 16.1
4  2018     March                 13.5
5  2018     April                 15.5
6  2018       May                 13.7

In [5]:
admissions_2018.tail()

    Year      Month Admissions (million)
9   2018     August                 19.2
10  2018  September                 10.1
11  2018    October                 16.0
12  2018   November                 14.8
13  2018   December                 15.7

#### Genres (2018)

In [6]:
genres_2018 = (
    tables_2018[1]
    .loc[4:21] # drop first 4 and last 2 rows
    .drop(columns=[2, 4])
)

genres_2018.insert(0, "Year", 2018)

genres_2018.columns = ["Year", "Genre", "Number of releases", "Gross box office (£ million)", "Top performing title"]

genres_2018.head()

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
4,2018,Action,77,361.3,Avengers: Infinity War
5,2018,Animation,46,242.2,Incredibles 2
6,2018,Drama,246,154.1,A Star Is Born
7,2018,Comedy,144,88.3,Johnny English Strikes Again
8,2018,Biopic,5,78.5,Bohemian Rhapsody

In [7]:
genres_2018.tail()

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
17,2018,Romance,17,11.8,The Guernsey Literary and Potato Peel Pie Society
18,2018,Documentary,112,9.3,Free Solo
19,2018,War,3,1.3,Journey’s End
20,2018,Western,2,0.1,Sweet Country
21,2018,Mystery,2,0.1,Dark River

#### Distributors (2018)

In [8]:
distributors_2018 = (
    tables_2018[3]
    .loc[5:] # drop first 5 rows
    .drop(index=[15, 17, 18]) # drop rows relating to totals EXCEPT the row totalling "others"
)

distributors_2018.insert(0, "Year", 2018)

distributors_2018.columns = ["Year", "Distributor", "Market share", "Films on release", "Box office gross (£ million)"]

distributors_2018.head()

,Year,Distributor,Market share,Films on release,Box office gross (£ million)
5,2018,Walt Disney,23.6,24,325.6
6,2018,Universal,19.5,40,268.5
7,2018,20th Century Fox,14.5,28,199.3
8,2018,Warner Bros,13.9,31,191.4
9,2018,Sony,10.7,33,146.8

In [9]:
distributors_2018.tail()

,Year,Distributor,Market share,Films on release,Box office gross (£ million)
11,2018,eOne Films,3.2,22,43.9
12,2018,StudioCanal,2.8,31,38.4
13,2018,Lionsgate,1.5,21,21.2
14,2018,Entertainment,1.1,9,15.6
16,2018,Others (128 distributors),4.5,715,61.4

# 2019

In [10]:
tables_2019 = extract_tables("./files/2020 - BFI Statistical Yearbook 2020 - 12815.pdf", pages="11,36,63")

Reading ./files/2020 - BFI Statistical Yearbook 2020 - 12815.pdf
5 tables found.

##########################
	Table 0
##########################

,0,1,2,3
0,,Table 1 Admissions in selected global territor...,,
1,Territory,Admissions 2018,Admissions 2019,+/- 2018 (%)
2,,(million),(million),
3,China,"1,717","1,727",0.6
4,India,"1,463","1,592",8.8
5,USA and Canada,"1,310","1,256",-4.1
6,Mexico,332,350,5.5
7,South Korea,216,227,4.8
8,Russia,200,219,9.5
9,France,201,213,6.0
10,Japan,169,195,15.2
11,UK,177,176,-0.5
12,Brazil,163,172,5.6
13,Indonesia,135,146,7.8
14,Germany,105,119,12.6
15,Italy,92,105,14.2
16,Spain,99,105,4.8
17,Poland,60,61,1.5
18,Turkey,70,59,-15.6
19,"Source: CAA, BFI, European Audiovisual Observa...",,,

##########################
	Table 1
##########################

,0,1,2,3
0,"Table 2 Monthly UK cinema admissions, 2018 and...",,,
1,Month,2018 (million),2019 (million),% +/- on 2018
2,January,16.2,13.7,-15.4
3,February,16.1,12.2,-24.0
4,March,13.5,11.4,-15.5
5,April,15.5,16.0,3.1
6,May,13.7,16.6,20.8
7,June,10.4,13.9,33.7
8,July,15.6,18.7,19.5
9,August,19.2,15.6,-19.1
10,September,10.1,11.0,8.2
11,October,16.1,16.3,1.8
12,November,14.9,12.2,-17.8
13,December,15.7,18.5,18.1
14,Total,177.0,176.1,-0.5
15,"Source: CAA, Comscore",,,

##########################
	Table 2
##########################

,0,1,2,3,4,5
0,Souvenir and Gwen.,,,,,
1,Table 10 Films released in the UK and Republic...,,,,,
2,Genre,Number of,% of,Gross,% of total,Top performing title
3,,releases,releases,box office,box office,
4,,,,(£ million),,
5,Action,102,13.4,328.3,25.2,Avengers: Endgame
6,Animation,40,5.2,312.1,24.0,The Lion King
7,Drama,264,34.6,166.4,12.8,Downton Abbey
8,Comedy,136,17.8,83.5,6.4,Yesterday
9,Biopic,19,2.5,80.7,6.2,Rocketman
10,Thriller,20,2.6,75.3,5.8,Joker
11,Sci-fi,3,0.4,64.3,4.9,Star Wars: The Rise of Skywalker
12,Horror,37,4.8,60.6,4.7,It Chapter Two
13,Adventure,8,1.0,44.5,3.4,Aladdin
14,Family,5,0.7,42.7,3.3,Dumbo
15,Romance,7,0.9,18.9,1.5,Last Christmas
16,Musical,8,1.0,12.3,0.9,Cats
17,Documentary,99,13.0,7.8,0.6,Apollo 11
18,Crime,11,1.4,2.8,0.2,21 Bridges
19,Mystery,1,0.1,0.5,<0.1,The Souvenir
20,War,2,0.3,0.1,<0.1,Saving Private Ryan (D-Day 75th Anniversary)
21,Fantasy,2,0.3,<0.1,<0.1,Gwen
22,Total,764,100.0,"1,300.9",100.0,
23,"Source: Comscore, BFI RSU analysis",,,,,

##########################
	Table 3
##########################

,0,1
0,DISTRIBUTORS,box office. Walt Disney’s market share is the ...
1,,achieved by a single distributor since our rec...
2,The top 10 feature film distributors in 2019 h...,"added to the total from 20th Century Fox, whic..."
3,of the market from the release of 248 titles (...,"acquired in early 2019, the total share would ..."
4,on release). The top 10 distributors in 2018 a...,Disney titles made up eight of the top 20 rele...
5,share from 251 releases (26% of films on relea...,including the year’s three highest earning fil...
6,130 film distributors were involved in the the...,"Endgame (£89 million), The Lion King (£76 mill..."
7,films in the UK and Republic of Ireland in 201...,Story 4 (£66 million). The second highest earn...
8,with 128 companies outside the top 10 in 2018....,"in 2019 was Universal, which released four of ..."
9,distributors outside the top 10 handled a tota...,20 titles including Downton Abbey (£28 million...
10,(73% of all films on release) but generated on...,Furious: Hobbs & Shaw (£21 million) and How to...
11,total box office.,Dragon: The Hidden World (£20 million).
12,Table 1 shows box office takings by distributo...,The top earning independent distributor in 201...
13,"on release during 2019, and hence includes rev...","Lionsgate, whose highest grossing titles were ..."
14,titles which were released in 2018 but remaine...,"(£13 million), John Wick: Chapter 3 – Parabell..."
15,into 2019. The top earning distributor was Wal...,and Angel Has Fallen (£7.5 million).
16,"total revenues of £507 million, a 38% share of...",
17,"Table 1 Distributor share of box office, UK an...",

##########################
	Table 4
##########################

,0,1,2,3
0,"total revenues of £507 million, a 38% share of...",,,
1,,"Table 1 Distributor share of box office, UK an...",,
2,Distributor,Market share,Films on release,Box office gross
3,,(%),in 2019,(£ million)
4,Walt Disney,37.9,24,506.8
5,Universal,13.9,39,185.6
6,Warner Bros,12.4,40,166.3
7,Sony,9.3,27,124.7
8,Paramount,5.9,13,79.0
9,20th Century Fox*,5.7,30,75.5
10,Lionsgate,4.2,19,56.4
11,Entertainment One,3.8,27,50.4
12,STX Entertainment,1.2,7,15.4
13,StudioCanal,1.0,22,14.0
14,Top 10,95.4,248,"1,274.1"
15,Others (Total 130 distributors),4.6,671,61.6
16,Total,100.0,919,"1,335.8"
17,Source: Comscore,,,

Here it looks like admissions is table 1.

Technically we could have extracted the 2018 figures from here as well. If we wanted a genre or distributor-level breakdown for 2018, we would have needed to open those PDFs anyway, so it doesn't make a difference.

If you were being really careful, you could also compare these figures with the ones in the 2018 PDF to make sure they match...

In [11]:
admissions_2019 = (
    tables_2019[1]
    .loc[2:13,[0, 2]] # ignore first two rows, last 2 rows, and keep first and third columns
)

admissions_2019.columns = ["Month", "Admissions (million)"]
admissions_2019.insert(0, "Year", 2019)

admissions_2019.head()

   Year     Month Admissions (million)
2  2019   January                 13.7
3  2019  February                 12.2
4  2019     March                 11.4
5  2019     April                 16.0
6  2019       May                 16.6

In [12]:
admissions_2019.tail()

    Year      Month Admissions (million)
9   2019     August                 15.6
10  2019  September                 11.0
11  2019    October                 16.3
12  2019   November                 12.2
13  2019   December                 18.5

#### Genres (2019)

In [13]:
genres_2019 = (
    tables_2019[2]
    .loc[5:21] # drop first 5 and last 2 rows
    .drop(columns=[2, 4])
)

genres_2019.insert(0, "Year", 2019)

genres_2019.columns = ["Year", "Genre", "Number of releases", "Gross box office (£ million)", "Top performing title"]

genres_2019.head(7)

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
5,2019,Action,102,328.3,Avengers: Endgame
6,2019,Animation,40,312.1,The Lion King
7,2019,Drama,264,166.4,Downton Abbey
8,2019,Comedy,136,83.5,Yesterday
9,2019,Biopic,19,80.7,Rocketman
10,2019,Thriller,20,75.3,Joker
11,2019,Sci-fi,3,64.3,Star Wars: The Rise of Skywalker

In [14]:
genres_2019.tail()

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
17,2019,Documentary,99,7.8,Apollo 11
18,2019,Crime,11,2.8,21 Bridges
19,2019,Mystery,1,0.5,The Souvenir
20,2019,War,2,0.1,Saving Private Ryan (D-Day 75th Anniversary)
21,2019,Fantasy,2,<0.1,Gwen

This code is very similar to the one for 2018. We *could* write a generic function to extract and transform a genre-level breakdown from any PDF, but we cannot assume they will all take the same form.

We generally don't want to assume data across multiple files will have the same format, but this is particularly true for PDF reports spanning many years.

#### Distributors (2019)

In [15]:
distributors_2019 = (
    tables_2019[4]
    .loc[4:]
    .drop(index=[14, 16, 17]) # drop totals EXCEPT the row totalling "others"
)

distributors_2019.insert(0, "Year", 2019)

distributors_2019.columns = ["Year", "Distributor", "Market share", "Films on release", "Box office gross (£ million)"]

distributors_2019.head()

,Year,Distributor,Market share,Films on release,Box office gross (£ million)
4,2019,Walt Disney,37.9,24,506.8
5,2019,Universal,13.9,39,185.6
6,2019,Warner Bros,12.4,40,166.3
7,2019,Sony,9.3,27,124.7
8,2019,Paramount,5.9,13,79.0

In [16]:
distributors_2019.tail()

,Year,Distributor,Market share,Films on release,Box office gross (£ million)
10,2019,Lionsgate,4.2,19,56.4
11,2019,Entertainment One,3.8,27,50.4
12,2019,STX Entertainment,1.2,7,15.4
13,2019,StudioCanal,1.0,22,14.0
15,2019,Others (Total 130 distributors),4.6,671,61.6

# 2020

In [17]:
tables_2020 = extract_tables("./files/2021 - BFI Statistical Yearbook 2021 - 24979.pdf", pages="10,35,60")

Reading ./files/2021 - BFI Statistical Yearbook 2021 - 24979.pdf
4 tables found.

##########################
	Table 0
##########################

,0,1,2,3,4,5,6
0,"Table 2 Monthly UK cinema admissions, 2016- 2020",,,,,,
1,Admissions,2016,2017,2018,2019,2020,% change
2,(million),,,,,,on 2019
3,January,14.0,15.0,16.2,13.7,16.5,20.4
4,February,15.4,16.5,16.1,12.2,14.5,19.0
5,March,13.4,16.2,13.5,11.4,4.8,-57.9
6,April,13.1,15.6,15.5,16.0,-,-100.0
7,May,12.5,11.3,13.7,16.6,-,-100.0
8,June,10.7,9.6,10.4,13.9,-,-100.0
9,July,16.6,17.8,15.6,18.7,0.4,-97.9
10,August,18.1,14.5,19.2,15.6,2.1,-86.7
11,September,11.7,10.8,10.1,11.0,2.7,-75.8
12,October,15.2,12.1,16.1,16.3,2.2,-86.6
13,November,12.4,14.1,14.9,12.2,0.3,-97.5
14,December,15.2,17.2,15.7,18.5,0.5,-97.2
15,Total,168.3,170.6,177.0,176.1,44.0,-75.0
16,"Source: CAA, Comscore",,,,,,

##########################
	Table 1
##########################

,0,1,2,3,4,5,6
0,"Gentlemen, and The Personal History of David C...",,,,,,
1,Table 10 Films released in the UK and Republic...,,,,,,
2,Genre,Number of,% of,Gross box,% of total,Average number,Top performing title
3,,releases,releases,office,box office,of sites at widest,
4,,,,(£ million),,point of release,
5,Action,36,9.4%,48.5,19.7%,167,Bad Boys For Life
6,War,3,0.8%,44.3,17.9%,296,1917
7,Animation,19,5.0%,34.8,14.1%,260,Sonic The Hedgehog
8,Thriller,15,3.9%,32.8,13.3%,192,Tenet
9,Drama,140,36.7%,31.4,12.7%,83,The Personal History of
10,,,,,,,David Copperfield
11,Comedy,65,17.1%,24.0,9.7%,108,Jojo Rabbit
12,Crime,8,2.1%,12.5,5.1%,118,The Gentlemen
13,Horror,24,6.3%,12.1,4.9%,172,The Invisible Man
14,Adventure,9,2.4%,3.8,1.6%,152,The Call Of The Wild
15,Fantasy,2,0.5%,0.9,0.4%,315,Pinocchio
16,Romance,6,1.6%,0.4,0.2%,30,Hope Gap
17,Documentary,42,11.0%,0.4,0.2%,19,I Am Greta
18,Western,2,0.5%,0.3,0.1%,53,True History Of The Kelly Gang
19,Family,3,0.8%,0.3,0.1%,85,Max Winslow And The
20,,,,,,,House Of Secrets
21,Biopic,3,0.8%,0.2,0.1%,16,Mr. Jones
22,Sci fi,4,1.0%,0.1,0.0%,18,Color Out Of Space
23,Total,381,100.0%,246.9,100.0%,110,
24,"Source: Comscore, BFI RSU analysis",,,,,,

##########################
	Table 2
##########################

,0,1,2,3,4
0,"Table 1 Distributor share of box office, UK an...",,,,
1,Distributor,Market share,Number of films,Box office,Number of films
2,,in 2020,on release,gross in 2020,on release
3,,(%),in 2020,(£ million),in 2019
4,Entertainment One,15.9,30,49.4,28
5,Sony,15.6,38,48.4,39
6,Walt Disney,14.3,58,44.3,47
7,Universal,12.5,73,39.0,55
8,Warner Bros,11.7,89,36.5,64
9,Paramount,8.0,22,25.0,13
10,Lionsgate,4.5,29,14.0,23
11,StudioCanal,4.5,46,13.9,31
12,Entertainment Film Distributors,4.3,6,13.3,10
13,Shear Entertainment*,1.3,1,4.0,n/a
14,Top 10,92.5,392,287.8,310
15,Other distributors (143),7.5,534,23.2,844
16,Total,100.0,926,311.0,"1,154"
17,Source: Comscore,,,,

##########################
	Table 3
##########################

,0,1,2,3,4,5,6,7,8,9,10
0,"4%, however, in 2020 this increased to 7.5%, t...",,,,,,,,,,
1,Table 2 Distributor market share as percentage...,,,,,,,,,,
2,Distributor,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
3,Entertainment One,5.1,6.7,9.0,8.0,3.9,8.4,2.5,3.2,3.8,15.9
4,Sony,7.2,18.0,8.7,6.2,11.8,6.6,10.3,10.7,9.3,15.6
5,Walt Disney,8.7,10.2,15.2,10.1,20.0,23.2,19.7,23.6,37.9,14.3
6,Universal,11.8,10.7,15.1,11.2,21.6,14.0,16.0,19.5,13.9,12.5
7,Warner Bros,18.2,12.9,17.2,15.9,9.0,15.6,16.6,13.9,12.4,11.7
8,Paramount,16.3,7.7,7.8,5.8,4.0,5.4,3.7,4.8,5.9,8.0
9,Lionsgate,-,5.7,4.7,5.5,4.0,4.0,6.3,1.5,4.2,4.5
10,Optimum/StudioCanal1,3.8,-,2.8,6.7,4.7,1.5,4.2,2.8,1.0,4.5
11,Entertainment Film Distributors,6.7,3.1,1.9,5.2,1.6,1.5,1.7,1.1,-,4.3
12,Shear Entertainment,-,-,-,-,-,-,-,-,-,1.3
13,20th Century Fox2,12.1,16.1,13.1,21.8,14.9,15.7,15.1,14.5,5.7,-
14,STX Entertainment,-,-,-,-,-,-,-,-,1.2,-
15,Momentum3,4.6,4.3,-,-,-,-,-,-,-,-
16,Top 10 total4,94.4,95.4,95.5,96.3,95.5,95.9,96.1,95.5,95.4,92.5
17,Others,5.6,4.6,4.5,3.7,4.5,4.1,3.9,4.5,4.6,7.5
18,Total,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
19,Source: Comscore,,,,,,,,,,

In [18]:
admissions_2020 = (
    tables_2020[0]
    .loc[3:14,[0,5]]
)

admissions_2020.columns = ["Month", "Admissions (million)"]
admissions_2020.insert(0, "Year", 2020)

admissions_2020.head()

   Year     Month Admissions (million)
3  2020   January                 16.5
4  2020  February                 14.5
5  2020     March                  4.8
6  2020     April                    -
7  2020       May                    -

Let's replace those hyphens with explicit missing (`NaN`) values

In [19]:
admissions_2020 = admissions_2020.replace("-", np.NaN)
admissions_2020.head()

   Year     Month Admissions (million)
3  2020   January                 16.5
4  2020  February                 14.5
5  2020     March                  4.8
6  2020     April                  NaN
7  2020       May                  NaN

In [20]:
admissions_2020.tail()

    Year      Month Admissions (million)
10  2020     August                  2.1
11  2020  September                  2.7
12  2020    October                  2.2
13  2020   November                  0.3
14  2020   December                  0.5

#### Genres

In [21]:
genres_2020 = (
    tables_2020[1]
    .loc[5:22] # drop first 5 and last 2 rows
    .drop(columns=[2, 4, 5])
)

genres_2020.insert(0, "Year", 2020)

genres_2020.columns = ["Year", "Genre", "Number of releases", "Gross box office (£ million)", "Top performing title"]

genres_2020.head(8)

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
5,2020,Action,36,48.5,Bad Boys For Life
6,2020,War,3,44.3,1917
7,2020,Animation,19,34.8,Sonic The Hedgehog
8,2020,Thriller,15,32.8,Tenet
9,2020,Drama,140,31.4,The Personal History of
10,2020,,,,David Copperfield
11,2020,Comedy,65,24.0,Jojo Rabbit
12,2020,Crime,8,12.5,The Gentlemen

In [22]:
genres_2020.tail()

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
18,2020,Western,2,0.3,True History Of The Kelly Gang
19,2020,Family,3,0.3,Max Winslow And The
20,2020,,,,House Of Secrets
21,2020,Biopic,3,0.2,Mr. Jones
22,2020,Sci fi,4,0.1,Color Out Of Space

Looks like a data error on row 10 and 20 - we might encounter a few of these where table rows spill over.

Let's manually fix these since we're here.

In [23]:
genres_2020.loc[9, "Top performing title"] = "The Personal History of David Copperfield"
genres_2020.loc[19, "Top performing title"] = "Max Winslow And The House Of Secrets"

genres_2020 = genres_2020.drop(index=[10, 20])
genres_2020.head()

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
5,2020,Action,36,48.5,Bad Boys For Life
6,2020,War,3,44.3,1917
7,2020,Animation,19,34.8,Sonic The Hedgehog
8,2020,Thriller,15,32.8,Tenet
9,2020,Drama,140,31.4,The Personal History of David Copperfield

In [24]:
genres_2020.tail()

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
17,2020,Documentary,42,0.4,I Am Greta
18,2020,Western,2,0.3,True History Of The Kelly Gang
19,2020,Family,3,0.3,Max Winslow And The House Of Secrets
21,2020,Biopic,3,0.2,Mr. Jones
22,2020,Sci fi,4,0.1,Color Out Of Space

#### Distributors

In [25]:
tables_2020[2]

,0,1,2,3,4
0,"Table 1 Distributor share of box office, UK an...",,,,
1,Distributor,Market share,Number of films,Box office,Number of films
2,,in 2020,on release,gross in 2020,on release
3,,(%),in 2020,(£ million),in 2019
4,Entertainment One,15.9,30,49.4,28
5,Sony,15.6,38,48.4,39
6,Walt Disney,14.3,58,44.3,47
7,Universal,12.5,73,39.0,55
8,Warner Bros,11.7,89,36.5,64
9,Paramount,8.0,22,25.0,13
10,Lionsgate,4.5,29,14.0,23
11,StudioCanal,4.5,46,13.9,31
12,Entertainment Film Distributors,4.3,6,13.3,10
13,Shear Entertainment*,1.3,1,4.0,n/a
14,Top 10,92.5,392,287.8,310
15,Other distributors (143),7.5,534,23.2,844
16,Total,100.0,926,311.0,"1,154"
17,Source: Comscore,,,,

In [26]:
distributors_2020 = (
    tables_2020[2]
    .loc[4:15,:3]
    .drop(index=[14]) # drop totals EXCEPT the row totalling "others"
)

distributors_2020.insert(0, "Year", 2020)

distributors_2020.columns = ["Year", "Distributor", "Market share", "Films on release", "Box office gross (£ million)"]

distributors_2020.head()

,Year,Distributor,Market share,Films on release,Box office gross (£ million)
4,2020,Entertainment One,15.9,30,49.4
5,2020,Sony,15.6,38,48.4
6,2020,Walt Disney,14.3,58,44.3
7,2020,Universal,12.5,73,39.0
8,2020,Warner Bros,11.7,89,36.5

In [27]:
distributors_2020.tail()

,Year,Distributor,Market share,Films on release,Box office gross (£ million)
10,2020,Lionsgate,4.5,29,14.0
11,2020,StudioCanal,4.5,46,13.9
12,2020,Entertainment Film Distributors,4.3,6,13.3
13,2020,Shear Entertainment*,1.3,1,4.0
15,2020,Other distributors (143),7.5,534,23.2

# 2021

In [28]:
tables_2021 = extract_tables('./files/2022 - The box office 2021 - full report - 26781.pdf', pages="6")

Reading ./files/2022 - The box office 2021 - full report - 26781.pdf
2 tables found.

##########################
	Table 0
##########################

,0,1
0,Shang-Chi’s three-day record was soon overtake...,"At 8.8 million, attendances in November were a..."
1,debut of another official 25th outing. The muc...,the level of October but were still the fourth...
2,"007 instalment, No Time to Die, originally sch...",year. Releases in the month include three top ...
3,"release in April 2020, grossed £21 million on ...",– Ghostbusters Afterlife and the UK studio-bac...
4,opening (£25.8 million including Thursday prev...,Eternals and House of Gucci – as well as the t...
5,highest Friday to Sunday tally for a Bond film...,"grossing UK independent film of the year, Spen..."
6,UK and Republic of Ireland. Officially release...,"Admissions rose again in December, despite con..."
7,"1 October, No Time to Die would go on to becom...",around the discovery of the COVID Omicron vari...
8,UK’s third highest ever release with a gross o...,biggest release of the month was Spider-Man: N...
9,and was the first film of the year to entice s...,"Home, which would go on to become the second h..."
10,numbers of older audience members back to the ...,grossing release of the year and the all-time ...
11,"Alongside three other top 20 earners – Dune, t...",highest earning film at the UK and Republic of...
12,studio-backed title Venom: Let There Be Carnag...,box office with earnings (to 13 February 2022) of
13,The Addams Family 2 – and the top earning UK,£93 million. Ticket sales for the month were a...
14,"independent film of the year, The French Dispa...","second highest of the year, with total admissi..."
15,Time to Die helped propel October’s ticket sal...,13.5 million.
16,highest total of the year at 16.4 million. Oct...,
17,only month to see an increase in admissions co...,
18,with the equivalent month in 2019.,
19,"Table 2 Monthly UK cinema admissions, 2019-2021",

##########################
	Table 1
##########################

,0,1,2,3,4
0,"Table 2 Monthly UK cinema admissions, 2019-2021",,,,
1,Admissions (million),2019,2020,2021,% change on 2019
2,January,13.7,16.5,-,-100.0
3,February,12.2,14.5,-,-100.0
4,March,11.4,4.8,-,-100.0
5,April,16.0,-,-,-100.0
6,May,16.6,-,3.5,-78.8
7,June,13.9,-,7.0,-49.9
8,July,18.7,0.4,7.8,-58.5
9,August,15.6,2.1,10.4,-33.1
10,September,11.0,2.7,6.5,-40.6
11,October,16.3,2.2,16.4,0.9
12,November,12.2,0.3,8.8,-27.5
13,December,18.5,0.5,13.5,-26.8
14,Total,176.1,44.0,74.0,-58.0
15,"Source: CAA, Comscore",,,,

Looks like Table 8 is monthly UK cinema admissions

In [29]:
admissions_2021 = (
    tables_2021[1]
    .loc[2:13]
    .drop(columns=[1, 2, 4])
)

admissions_2021.columns = ["Month", "Admissions (million)"]
admissions_2021.insert(0, "Year", 2021)

admissions_2021["Admissions (million)"] = admissions_2021["Admissions (million)"].replace("-", np.NaN)

admissions_2021.head()

   Year     Month Admissions (million)
2  2021   January                  NaN
3  2021  February                  NaN
4  2021     March                  NaN
5  2021     April                  NaN
6  2021       May                  3.5

In [30]:
admissions_2021.tail()

    Year      Month Admissions (million)
9   2021     August                 10.4
10  2021  September                  6.5
11  2021    October                 16.4
12  2021   November                  8.8
13  2021   December                 13.5

#### Genres

For the first time these stats are actually in another PDF

In [31]:
tables_2021_genre = extract_tables("./files/2022 - Top films in 2021 - full report - 29763.pdf", pages="13")

Reading ./files/2022 - Top films in 2021 - full report - 29763.pdf
1 tables found.

##########################
	Table 0
##########################

,0,1,2,3,4,5,6
0,Table 9 Films released in the UK and Republic ...,,,,,,
1,Genre,Number,% of,Box office,% of,Average number,Top performing title
2,,of releas-,releases,gross,total,of sites at,
3,,es,,(£ million),box office,widest point,
4,,,,,,of release,
5,Action,52,11.8,296.7,48.2,210,No Time to Die
6,Comedy,54,12.2,65.1,10.6,138,Free Guy
7,Animation,38,8.6,58.2,9.4,260,The Addams Family 2
8,Horror,24,5.4,40.8,6.6,277,A Quiet Place Part II
9,Family,8,1.8,29.6,4.8,187,Peter Rabbit 2: The Runaway
10,Sci fi,4,0.9,29.6,4.8,420,Dune
11,Drama,134,30.3,20.6,3.3,78,Nomadland
12,Musical,8,1.8,15.5,2.5,313,West Side Story
13,Adventure,6,1.4,15.2,2.5,243,Jungle Cruise
14,Fantasy,3,0.7,14.9,2.4,263,Eternals
15,Biopic,5,1.1,13.4,2.2,345,House of Gucci
16,Thriller,10,2.3,8.2,1.3,173,The Forever Purge
17,Suspense,12,2.7,4.5,0.7,117,Old
18,Documentary,69,15.6,2.1,0.3,22,"Summer of Soul (...Or, When"
19,,,,,,,the Revolution Could
20,,,,,,,Not Be Televised)
21,Romance,13,2.9,1.5,0.2,77,The Last Letter from Your Lover
22,Crime,2,0.5,0.3,<0.1,137,Rise of the Footsoldier: Origins
23,Total,442,100.0,616.2,100.0,138,
24,"Source: Comscore, BFI RSU analysis",,,,,,

In [32]:
genres_2021 = (
    tables_2021_genre[0]
    .loc[5:22]
    .drop(columns=[2, 4, 5])
)

genres_2021.insert(0, "Year", 2021)

genres_2021.columns = ["Year", "Genre", "Number of releases", "Gross box office (£ million)", "Top performing title"]

# fix data error
genres_2021.loc[18, "Top performing title"] = "Summer of Soul (...Or, When the Revolution Could Not Be Televised)"
genres_2021 = genres_2021.drop(index=[19, 20])

genres_2021.head()

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
5,2021,Action,52,296.7,No Time to Die
6,2021,Comedy,54,65.1,Free Guy
7,2021,Animation,38,58.2,The Addams Family 2
8,2021,Horror,24,40.8,A Quiet Place Part II
9,2021,Family,8,29.6,Peter Rabbit 2: The Runaway

In [33]:
genres_2021.tail()

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
16,2021,Thriller,10,8.2,The Forever Purge
17,2021,Suspense,12,4.5,Old
18,2021,Documentary,69,2.1,"Summer of Soul (...Or, When the Revolution Cou..."
21,2021,Romance,13,1.5,The Last Letter from Your Lover
22,2021,Crime,2,0.3,Rise of the Footsoldier: Origins

#### Distributors

In [34]:
tables_2021_dist = extract_tables("./files/2022 - Distribution - full report - 26782.pdf", pages="4")

Reading ./files/2022 - Distribution - full report - 26782.pdf
2 tables found.

##########################
	Table 0
##########################

,0,1
0,,Table 1 shows box office takings by distributo...
1,Distributors,
2,,films on release in the UK and Republic of Ire...
3,,2021 (including titles released prior to 2021)...
4,,earning distributor was Universal which releas...
5,A strong recovery in the numbers of people cho...,highest earning film of the year No Time to Di...
6,watch films on the big screen made 2021 a more,four other top 20 titles including Fast & Furi...
7,successful year for the distribution sector th...,"Addams Family 2. In total, titles released by ..."
8,Despite continued challenges from the COVID-19,generated revenues of £181 million in 2021 (a ...
9,"pandemic, which saw all cinemas closed for the...",of overall box office). The second highest ear...
10,"to six months of the year, a total of 981 film...",distributor in 2021 was Sony which released fo...
11,"release theatrically during 2021, compared wit...","year’s top 20 titles, including Spider-Man: No..."
12,"in 2020 (1,154 in 2019). Cinemas reopened in E...",Peter Rabbit 2: The Runaway and Ghostbusters: ...
13,"Scotland and Wales from 17 May, in Northern Ir...","Sony releases earned £131 million in 2021, a 2..."
14,from 24 May and in the Republic of Ireland fro...,of the box office.
15,The top 10 feature film distributors had a 97%...,"The appearance in the top 10 of Park Circus, w..."
16,the market in 2021 from the release of 432 tit...,specialises in classic and back catalogue titl...
17,all films on release). The share is the highes...,the importance of older releases to cinemas du...
18,and up almost five percentage points from 2020...,two years most impacted by the pandemic. The
19,the top 10 distributors had a market share of ...,newcomer to the list had 96 titles on release ...
20,392 releases (42% of all releases). A further 137,the greatest number of any of the top 10 distr...
21,distributors were involved in the theatrical r...,
22,"in the UK and Republic of Ireland in 2021, com...",
23,143 companies outside the top 10 in 2020. These,
24,distributors handled a total of 549 titles (56...,
25,releases) but generated only 3% of the total b...,
26,"Table 1 Distributor share of box office, UK an...",

##########################
	Table 1
##########################

,0,1,2,3
0,"Table 1 Distributor share of box office, UK an...",,,
1,Distributor,Market share in 2021 (%),Films on release in 2021,Box office gross in 2021
2,,,,(£ million)
3,Universal,30.6,51,180.8
4,Sony,22.2,52,130.8
5,Walt Disney,21.2,63,125.1
6,Warner Bros,14.4,80,84.7
7,Paramount,3.7,16,21.8
8,Lionsgate,1.8,23,10.5
9,Entertainment One,1.4,12,8.1
10,Park Circus,0.6,96,3.4
11,STX Entertainment,0.6,3,3.4
12,StudioCanal,0.5,36,2.7
13,Top 10,96.8,432,571.2
14,Other distributors (137),3.2,549,19.0
15,Total,100.0,981,590.2
16,Source: Comscore,,,

In [35]:
distributors_2021 = (
    tables_2021_dist[1]
    .loc[3:14]
    .drop(index=[13]) # drop Top 10 total row
)

distributors_2021.insert(0, "Year", 2021)
distributors_2021.columns = ["Year", "Distributor", "Market share", "Films on release", "Box office gross (£ million)"]
distributors_2021.head()

,Year,Distributor,Market share,Films on release,Box office gross (£ million)
3,2021,Universal,30.6,51,180.8
4,2021,Sony,22.2,52,130.8
5,2021,Walt Disney,21.2,63,125.1
6,2021,Warner Bros,14.4,80,84.7
7,2021,Paramount,3.7,16,21.8

In [36]:
distributors_2021.tail()

,Year,Distributor,Market share,Films on release,Box office gross (£ million)
9,2021,Entertainment One,1.4,12,8.1
10,2021,Park Circus,0.6,96,3.4
11,2021,STX Entertainment,0.6,3,3.4
12,2021,StudioCanal,0.5,36,2.7
14,2021,Other distributors (137),3.2,549,19.0

# Combine everything

In [37]:
admissions = pd.concat([admissions_2018, admissions_2019, admissions_2020, admissions_2021],
                       ignore_index=True,
                       axis=0)

admissions.head()

   Year     Month Admissions (million)
0  2018   January                 16.2
1  2018  February                 16.1
2  2018     March                 13.5
3  2018     April                 15.5
4  2018       May                 13.7

In [38]:
admissions["Year"].value_counts()

2018    12
2019    12
2020    12
2021    12
Name: Year, dtype: int64

In [39]:
admissions.to_csv("admissions.csv", index=False)

#### Genres

In [40]:
genres = pd.concat([genres_2018, genres_2019, genres_2020, genres_2021],
                   ignore_index=True,
                   axis=0)

genres.head()

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
0,2018,Action,77,361.3,Avengers: Infinity War
1,2018,Animation,46,242.2,Incredibles 2
2,2018,Drama,246,154.1,A Star Is Born
3,2018,Comedy,144,88.3,Johnny English Strikes Again
4,2018,Biopic,5,78.5,Bohemian Rhapsody

In [41]:
genres.tail()

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
62,2021,Thriller,10,8.2,The Forever Purge
63,2021,Suspense,12,4.5,Old
64,2021,Documentary,69,2.1,"Summer of Soul (...Or, When the Revolution Cou..."
65,2021,Romance,13,1.5,The Last Letter from Your Lover
66,2021,Crime,2,0.3,Rise of the Footsoldier: Origins

In [42]:
genres["Year"].value_counts()

2018    18
2019    17
2020    16
2021    16
Name: Year, dtype: int64

In [43]:
genres.to_csv("genres.csv", index=False)

#### Distributors

In [44]:
distributors = pd.concat([distributors_2018, distributors_2019, distributors_2020, distributors_2021],
                         ignore_index=True,
                         axis=0)

distributors.head()

,Year,Distributor,Market share,Films on release,Box office gross (£ million)
0,2018,Walt Disney,23.6,24,325.6
1,2018,Universal,19.5,40,268.5
2,2018,20th Century Fox,14.5,28,199.3
3,2018,Warner Bros,13.9,31,191.4
4,2018,Sony,10.7,33,146.8

In [45]:
distributors.tail()

,Year,Distributor,Market share,Films on release,Box office gross (£ million)
39,2021,Entertainment One,1.4,12,8.1
40,2021,Park Circus,0.6,96,3.4
41,2021,STX Entertainment,0.6,3,3.4
42,2021,StudioCanal,0.5,36,2.7
43,2021,Other distributors (137),3.2,549,19.0

In [46]:
distributors["Year"].value_counts()

2018    11
2019    11
2020    11
2021    11
Name: Year, dtype: int64

In [47]:
distributors.to_csv("distributors.csv", index=False)