In [ ]:
# Import the necessary libraries
# Read the following dataset into a pandas dataframe: 'source/tourist_arrivals_countries.csv' and parse the Date field as a date
# Remove missing rows from the data
# Extract the year from the Date field and create a new column called Year
# Group the data by Year and calculate the average number of tourist arrivals for each year
# Select only the rows where the year is 1994 or 2018
# Select only the following columns: Year, PT and DE
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import os
import sys
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Read the following dataset into a pandas dataframe: 'source/tourist_arrivals_countries.csv' and parse the Date field as a date
df = pd.read_csv('/content/tourist_arrivals_countries.csv', parse_dates=['Date'])

# Remove missing rows from the data
df = df.dropna()

# Extract the year from the Date field and create a new column called Year
df['Year'] = df['Date'].dt.year

# Group the data by Year and calculate the average number of tourist arrivals for each year
df = df.groupby('Year').mean()

# Select only the rows where the year is 1994 or 2018
df = df.loc[[1994, 2018]]

# Select only the following# Create a new dataframe df_pi with three columns Year, Country, and Percentage Increase
# Add a new row to df_pi with the following values: 1994, PT, 0.0
# Add a new row to df_pi with the following values: 1994, DE, 0.0
# For columns PT and DE in the original dataframe df,
#   calculate the percentage increase of the second row respect to first row and
#   store the result as two new columns in df_pi. For the column year, add 2018

df_pi = pd.DataFrame(columns=['Year', 'Country', 'Percentage Increase'])
df_pi = df_pi.append({'Year': 1994, 'Country': 'PT', 'Percentage Increase': 0.0}, ignore_index=True)
df_pi = df_pi.append({'Year': 1994, 'Country': 'DE', 'Percentage Increase': 0.0}, ignore_index=True)

df_pi = df_pi.append({'Year': 2018, 'Country': 'PT', 'Percentage Increase': (df.loc[2018, 'PT'] - df.loc[1994, 'PT']) / df.loc[1994, 'PT']}, ignore_index=True)
df_pi = df_pi.append({'Year': 2018, 'Country': 'DE', 'Percentage Increase': (df.loc[2018, 'DE'] - df.loc[1994, 'DE']) / df.loc[1994, 'DE']}, ignore_index=True)

df_pi columns: Year, PT and DE
df = df[['PT', 'DE']]
df

                PT            DE
Year
1994  5.633548e+05  5.617487e+06
2018  1.703339e+06  1.213249e+07

In [ ]:
# Create a new dataframe df_pi with three columns Year, Country, and Percentage Increase
# Add a new row to df_pi with the following values: 1994, PT, 0.0
# Add a new row to df_pi with the following values: 1994, DE, 0.0
# For columns PT and DE in the original dataframe df,
#   calculate the percentage increase of the second row respect to first row and
#   store the result as two new columns in df_pi. For the column year, add 2018

df_pi = pd.DataFrame(columns=['Year', 'Country', 'Percentage Increase'])
df_pi = df_pi.append({'Year': 1994, 'Country': 'PT', 'Percentage Increase': 0.0}, ignore_index=True)
df_pi = df_pi.append({'Year': 1994, 'Country': 'DE', 'Percentage Increase': 0.0}, ignore_index=True)

df_pi = df_pi.append({'Year': 2018, 'Country': 'PT', 'Percentage Increase': (df.loc[2018, 'PT'] - df.loc[1994, 'PT']) / df.loc[1994, 'PT']}, ignore_index=True)
df_pi = df_pi.append({'Year': 2018, 'Country': 'DE', 'Percentage Increase': (df.loc[2018, 'DE'] - df.loc[1994, 'DE']) / df.loc[1994, 'DE']}, ignore_index=True)

df_pi

   Year Country  Percentage Increase
0  1994      PT             0.000000
1  1994      DE             0.000000
2  2018      PT             2.023563
3  2018      DE             1.159772

In [ ]:
# Use the Altair library to plot two lines in the same chart
# showing the PT and DE columns versus the Year column of df_pi.
# Use the color channel to discriminate for the Country column.
# Encode the x channel as ordinal. Set chart width to 400
import altair as alt

alt.Chart(df_pi).mark_line().encode(
    x=alt.X('Year:O'),
    y='Percentage Increase',
    color='Country'
).properties(
    width=400
)

alt.Chart(...)

In [ ]:
# Create a new chart with the following text: 'Thanks to the introduction of low-cost flights,Portugal has experienced an increase in tourist arrivals of over 200% in 25 years, even surpassing the increase in Germany, one of the favorite destinations for tourists ever.' Use the as a line break to format the text. Set the font size to 14.
# Place the two graphs side by side. Set the title to 'Yes, you can build a new swimming pool!'
# Save the chart as an HTML. Name the file output.html
text = 'Thanks to the introduction of low-cost flights, Portugal has experienced an increase in tourist arrivals of over 200% in 25 years, even surpassing the increase in Germany, one of the favorite destinations for tourists ever.'

chart1 = alt.Chart(df_pi).mark_line().encode(
    x=alt.X('Year:O'),
    y='Percentage Increase',
    color='Country'
).properties(
    width=400
)

chart2 = alt.Chart().mark_text(
    text=text,
    fontSize=14
).properties(
    width=400
)

# chart1 | chart2

# chart1 | chart2.save('output_copilot.html')

combined_chart = chart1 | chart2
combined_chart.save('output_copilot.html')