In [5]:
# import necessary libraries

# !pip install pdfplumber

Collecting pdfplumber
  Downloading pdfplumber-0.10.3-py3-none-any.whl (48 kB)
     -------------------------------------- 49.0/49.0 kB 614.5 kB/s eta 0:00:00
Requirement already satisfied: Pillow>=9.1 in c:\users\gcart\anaconda3\lib\site-packages (from pdfplumber) (9.2.0)
Collecting pdfminer.six==20221105
  Downloading pdfminer.six-20221105-py3-none-any.whl (5.6 MB)
     ---------------------------------------- 5.6/5.6 MB 1.3 MB/s eta 0:00:00
Collecting pypdfium2>=4.18.0
  Downloading pypdfium2-4.23.1-py3-none-win_amd64.whl (2.7 MB)
     ---------------------------------------- 2.7/2.7 MB 811.9 kB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\gcart\anaconda3\lib\site-packages (from pdfminer.six==20221105->pdfplumber) (2.0.4)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\gcart\anaconda3\lib\site-packages (from pdfminer.six==20221105->pdfplumber) (37.0.1)
Requirement already satisfied: cffi>=1.12 in c:\users\gcart\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20221105->pdfplumber) (1.15.1)
Requirement already satisfied: pycparser in c:\users\gcart\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20221105->pdfplumber) (2.21)
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20221105 pdfplumber-0.10.3 pypdfium2-4.23.1

In [6]:
import numpy as np
import pandas as pd
 
import pdfplumber
 
from IPython.display import display

In [9]:
# the following code will open the PDF, enumerate through the pages, and extract all the tables it identifies.

pdf_path = "C:/Users/gcart/OneDrive/Documents/dev/r/projs/book_reviews/solve_any_data_analysis_problem_projs/CH05_asboth_Solve_Any_Data_Analysis_Problem/files/2019 - BFI yearbook 2019 - 888.pdf"
page_num = 11
 
page_tables = []
 
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[page_num-1]
    # page_tables is a list of lists of lists(!)
    # extracted from special Table objects
    page_tables = [t.extract() for t in page.find_tables()]
 

page_tables

[[['Month', '2017 (million)', '2018 (million)', '% +/- on 2017'],
  ['January', '15.0', '16.2', '8.0'],
  ['February', '16.5', '16.1', '-2.3'],
  ['March', '16.2', '13.5', '-16.2'],
  ['April', '15.6', '15.5', '-0.9'],
  ['May', '11.3', '13.7', '21.0'],
  ['June', '9.6', '10.4', '8.6'],
  ['July', '17.8', '15.6', '-12.3'],
  ['August', '14.5', '19.2', '32.8'],
  ['September', '10.8', '10.1', '-6.0'],
  ['October', '12.1', '16.0', '32.6'],
  ['November', '14.1', '14.8', '5.4'],
  ['December', '17.2', '15.7', '-8.7'],
  ['Total', '170.6', '177.0', '3.7']]]

In [10]:
 # convert this to a list of DataFrames
    
table = page_tables[0]
pd.DataFrame(table[1:-1], columns=table[0])

        Month 2017 (million) 2018 (million) % +/- on 2017
0     January           15.0           16.2           8.0
1    February           16.5           16.1          -2.3
2       March           16.2           13.5         -16.2
3       April           15.6           15.5          -0.9
4         May           11.3           13.7          21.0
5        June            9.6           10.4           8.6
6        July           17.8           15.6         -12.3
7      August           14.5           19.2          32.8
8   September           10.8           10.1          -6.0
9     October           12.1           16.0          32.6
10   November           14.1           14.8           5.4
11   December           17.2           15.7          -8.7

In [13]:
# These code snippets can then be extended to work across multiple pages

def extract_tables(pdf_path, pages=[], print_tables=True):
  """
  Extract all tables found in a PDF.
    
  `pdf_path`: file path pointing to the PDF
  `pages`: the page number(s) to read
  `print_tables`: whether to also print out
  all the tables that are found (default: True)
    
  returns: a list of pandas DataFrames
  """
    
  print(f"Reading {pdf_path}")
    
  tables = []
    
  with pdfplumber.open(pdf_path) as pdf:
      for page_num in pages:
          page = pdf.pages[page_num-1]
            
          # page_tables is a list of lists of lists(!)
          # extracted from special Table objects
          page_tables = [t.extract() for t in page.find_tables()]
            
          # in each case, table is now a list of lists
          # first list is column headers
          df = [pd.DataFrame(table[1:-1], columns=table[0]) for table in page_tables]
            
          tables.extend(df)
    
  print(f"{len(tables)} tables found.")
    
  if len(tables) > 0:
    if print_tables:
        for index, df in enumerate(tables):
          print(f"\n##########################\n\tTable {index}\n##########################\n")
          display(df)
    
  return tables
 
tables = extract_tables("C:/Users/gcart/OneDrive/Documents/dev/r/projs/book_reviews/solve_any_data_analysis_problem_projs/CH05_asboth_Solve_Any_Data_Analysis_Problem/files/2019 - BFI yearbook 2019 - 888.pdf", pages=[11,34,70])

Reading C:/Users/gcart/OneDrive/Documents/dev/r/projs/book_reviews/solve_any_data_analysis_problem_projs/CH05_asboth_Solve_Any_Data_Analysis_Problem/files/2019 - BFI yearbook 2019 - 888.pdf
3 tables found.

##########################
	Table 0
##########################

        Month 2017 (million) 2018 (million) % +/- on 2017
0     January           15.0           16.2           8.0
1    February           16.5           16.1          -2.3
2       March           16.2           13.5         -16.2
3       April           15.6           15.5          -0.9
4         May           11.3           13.7          21.0
5        June            9.6           10.4           8.6
6        July           17.8           15.6         -12.3
7      August           14.5           19.2          32.8
8   September           10.8           10.1          -6.0
9     October           12.1           16.0          32.6
10   November           14.1           14.8           5.4
11   December           17.2           15.7          -8.7

##########################
	Table 1
##########################

,Genre,Number of\nreleases,% of\nreleases,Gross box\noffice\n(£ million),% of total\nbox office,Top performing title
0,Action,77,9.8,361.3,27.7,Avengers: Infinity War
1,Animation,46,5.8,242.2,18.6,Incredibles 2
2,Drama,246,31.3,154.1,11.8,A Star Is Born
3,Comedy,144,18.3,88.3,6.8,Johnny English Strikes Again
4,Biopic,5,0.6,78.5,6.0,Bohemian Rhapsody
5,Musical,5,0.6,67.0,5.1,Mamma Mia! Here We Go Again
6,Family,10,1.3,60.3,4.6,Mary Poppins Returns
7,Fantasy,4,0.5,57.6,4.4,Fantastic Beasts: The Crimes of Grindelwald
8,Horror,38,4.8,57.1,4.4,A Quiet Place
9,Adventure,10,1.3,36.4,2.8,Ready Player One
10,Sci-fi,14,1.8,30.8,2.4,Solo: A Star Wars Story
11,Thriller,42,5.3,30.6,2.3,The Equalizer 2
12,Crime,10,1.3,17.9,1.4,Widows
13,Romance,17,2.2,11.8,0.9,The Guernsey Literary and Potato Peel Pie Society
14,Documentary,112,14.2,9.3,0.7,Free Solo
15,War,3,0.4,1.3,0.1,Journey’s End
16,Western,2,0.3,0.1,<0.1,Sweet Country
17,Mystery,2,0.3,0.1,<0.1,Dark River

##########################
	Table 2
##########################

,Distributor,Market share\n(%),Films on release\nin 2018,Box office gross\n(£ million)
0,Walt Disney,23.6,24,325.6
1,Universal,19.5,40,268.5
2,20th Century Fox,14.5,28,199.3
3,Warner Bros,13.9,31,191.4
4,Sony,10.7,33,146.8
5,Paramount,4.8,12,66.0
6,eOne Films,3.2,22,43.9
7,StudioCanal,2.8,31,38.4
8,Lionsgate,1.5,21,21.2
9,Entertainment,1.1,9,15.6
10,Top 10 total,95.5,251,"1,316.8"
11,Others (128 distributors),4.5,715,61.4

In [15]:
# e identify the page numbers of interest and use our function to extract the admissions, genre, and distributor data

tables_2018 = extract_tables("C:/Users/gcart/OneDrive/Documents/dev/r/projs/book_reviews/solve_any_data_analysis_problem_projs/CH05_asboth_Solve_Any_Data_Analysis_Problem/files/2019 - BFI yearbook 2019 - 888.pdf", pages=[11,34,70])

Reading C:/Users/gcart/OneDrive/Documents/dev/r/projs/book_reviews/solve_any_data_analysis_problem_projs/CH05_asboth_Solve_Any_Data_Analysis_Problem/files/2019 - BFI yearbook 2019 - 888.pdf
3 tables found.

##########################
	Table 0
##########################

        Month 2017 (million) 2018 (million) % +/- on 2017
0     January           15.0           16.2           8.0
1    February           16.5           16.1          -2.3
2       March           16.2           13.5         -16.2
3       April           15.6           15.5          -0.9
4         May           11.3           13.7          21.0
5        June            9.6           10.4           8.6
6        July           17.8           15.6         -12.3
7      August           14.5           19.2          32.8
8   September           10.8           10.1          -6.0
9     October           12.1           16.0          32.6
10   November           14.1           14.8           5.4
11   December           17.2           15.7          -8.7

##########################
	Table 1
##########################

,Genre,Number of\nreleases,% of\nreleases,Gross box\noffice\n(£ million),% of total\nbox office,Top performing title
0,Action,77,9.8,361.3,27.7,Avengers: Infinity War
1,Animation,46,5.8,242.2,18.6,Incredibles 2
2,Drama,246,31.3,154.1,11.8,A Star Is Born
3,Comedy,144,18.3,88.3,6.8,Johnny English Strikes Again
4,Biopic,5,0.6,78.5,6.0,Bohemian Rhapsody
5,Musical,5,0.6,67.0,5.1,Mamma Mia! Here We Go Again
6,Family,10,1.3,60.3,4.6,Mary Poppins Returns
7,Fantasy,4,0.5,57.6,4.4,Fantastic Beasts: The Crimes of Grindelwald
8,Horror,38,4.8,57.1,4.4,A Quiet Place
9,Adventure,10,1.3,36.4,2.8,Ready Player One
10,Sci-fi,14,1.8,30.8,2.4,Solo: A Star Wars Story
11,Thriller,42,5.3,30.6,2.3,The Equalizer 2
12,Crime,10,1.3,17.9,1.4,Widows
13,Romance,17,2.2,11.8,0.9,The Guernsey Literary and Potato Peel Pie Society
14,Documentary,112,14.2,9.3,0.7,Free Solo
15,War,3,0.4,1.3,0.1,Journey’s End
16,Western,2,0.3,0.1,<0.1,Sweet Country
17,Mystery,2,0.3,0.1,<0.1,Dark River

##########################
	Table 2
##########################

,Distributor,Market share\n(%),Films on release\nin 2018,Box office gross\n(£ million)
0,Walt Disney,23.6,24,325.6
1,Universal,19.5,40,268.5
2,20th Century Fox,14.5,28,199.3
3,Warner Bros,13.9,31,191.4
4,Sony,10.7,33,146.8
5,Paramount,4.8,12,66.0
6,eOne Films,3.2,22,43.9
7,StudioCanal,2.8,31,38.4
8,Lionsgate,1.5,21,21.2
9,Entertainment,1.1,9,15.6
10,Top 10 total,95.5,251,"1,316.8"
11,Others (128 distributors),4.5,715,61.4

In [16]:
# add a Year column. We also do not need 2017 data or the percentage change, so we can drop those columns

admissions_2018 = (
    tables_2018[0]
    .iloc[:,[0, 2]]
)
 
admissions_2018.columns = ["Month", "Admissions (million)"]
 
admissions_2018.insert(0, "Year", 2018)
 
admissions_2018.head()

   Year     Month Admissions (million)
0  2018   January                 16.2
1  2018  February                 16.1
2  2018     March                 13.5
3  2018     April                 15.5
4  2018       May                 13.7

In [17]:
# add a Year column to differentiate genres across years, we do not need all the columns, and we will need to clean up the 
# column names to remove the \n newline characters.

genres_2018 = (
    tables_2018[1]
    .drop(columns=[tables_2018[1].columns[2], tables_2018[1].columns[4]])
)
 
genres_2018.insert(0, "Year", 2018)
 
genres_2018.columns = ["Year", "Genre", "Number of releases","Gross box office (£ million)", "Top performing title"]
 
genres_2018.head()

,Year,Genre,Number of releases,Gross box office (£ million),Top performing title
0,2018,Action,77,361.3,Avengers: Infinity War
1,2018,Animation,46,242.2,Incredibles 2
2,2018,Drama,246,154.1,A Star Is Born
3,2018,Comedy,144,88.3,Johnny English Strikes Again
4,2018,Biopic,5,78.5,Bohemian Rhapsody

In [18]:
# add the Year column again, remove row 10, as it is a total of the rows above it

distributors_2018 = (
    tables_2018[2]
    .drop(index=[10]) # drop the top 10 total row
)
 
distributors_2018.insert(0, "Year", 2018)
 
distributors_2018.columns = ["Year", "Distributor", "Market share","Films on release", "Box office gross (£ million)"]
 
distributors_2018.head()

,Year,Distributor,Market share,Films on release,Box office gross (£ million)
0,2018,Walt Disney,23.6,24,325.6
1,2018,Universal,19.5,40,268.5
2,2018,20th Century Fox,14.5,28,199.3
3,2018,Warner Bros,13.9,31,191.4
4,2018,Sony,10.7,33,146.8